language: node_js
node_js:
- "12"  # nodejs的版本
branches:
  only:
  - hexo  # 设置自动化部署的源码分支
before_install:
- export TZ='Asia/Shanghai'  
# - npm install -g hexo
# - npm install -g hexo-cli 
# - npm install -g yarn
before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "Asuri Robot"
- git config --global user.email "xm1994+asuri-robot@gmail.com" 
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
- sed -i'' "s~git@github.com:Asuri-Team/Asuri-Team.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/Asuri-Team/Asuri-Team.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- ./node_modules/.bin/hexo clean
- ./node_modules/.bin/hexo generate
# 执行的成功后执行 
after_success:
- ./node_modules/.bin/hexo deploy
